# fly.toml app configuration file generated for power-jskp-api on 2023-08-17T13:49:40+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "power-jskp-api"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8121
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
